name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Test
        run: cargo test --all-targets --no-fail-fast
      - name: Lint
        run: cargo clippy --all-targets -- -D warnings
